// flow-typed signature: 912fcc7f95c85745f7f7efa68462e88a
// flow-typed version: <<STUB>>/@types/mocha_v^2.2.32/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mocha' {
  declare module.exports: any;
}
