// flow-typed signature: e3b2f365b9d3b3331e6873523fbfcab7
// flow-typed version: <<STUB>>/@types/node_v^6.0.40/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
